name: news_app
description: A simple app which fetches news articles from user's provided domains.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  timeago: ^3.5.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.0.1
  custom_lint: ^0.5.2
  json_serializable: ^6.7.1
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
